// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ3mFhk65e1wymQCvfp_NwspTcNvywHww',
    appId: '1:875221166519:web:c138693a3518c0bf472032',
    messagingSenderId: '875221166519',
    projectId: 'hciproject-68016',
    authDomain: 'hciproject-68016.firebaseapp.com',
    storageBucket: 'hciproject-68016.firebasestorage.app',
    measurementId: 'G-0XRW8NP5R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWku6m9M18E6kewaBQ0hmuxLaUgDukLO0',
    appId: '1:875221166519:android:f9afc0a88b7537a6472032',
    messagingSenderId: '875221166519',
    projectId: 'hciproject-68016',
    storageBucket: 'hciproject-68016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLsc_4U_4D4NLOQtjmNuZ75hZ3D2jQTz8',
    appId: '1:875221166519:ios:f972d22b56b12e0d472032',
    messagingSenderId: '875221166519',
    projectId: 'hciproject-68016',
    storageBucket: 'hciproject-68016.firebasestorage.app',
    iosBundleId: 'com.example.hciFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLsc_4U_4D4NLOQtjmNuZ75hZ3D2jQTz8',
    appId: '1:875221166519:ios:f972d22b56b12e0d472032',
    messagingSenderId: '875221166519',
    projectId: 'hciproject-68016',
    storageBucket: 'hciproject-68016.firebasestorage.app',
    iosBundleId: 'com.example.hciFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ3mFhk65e1wymQCvfp_NwspTcNvywHww',
    appId: '1:875221166519:web:776281657baf70f8472032',
    messagingSenderId: '875221166519',
    projectId: 'hciproject-68016',
    authDomain: 'hciproject-68016.firebaseapp.com',
    storageBucket: 'hciproject-68016.firebasestorage.app',
    measurementId: 'G-PMZHRXB90T',
  );
}
